#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-tweaks
Version  : 3.30.0
Release  : 1
URL      : https://gitlab.gnome.org/GNOME/gnome-tweaks/-/archive/3.30.0/gnome-tweaks-3.30.0.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/gnome-tweaks/-/archive/3.30.0/gnome-tweaks-3.30.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0
Requires: gnome-tweaks-bin
Requires: gnome-tweaks-python3
Requires: gnome-tweaks-data
Requires: gnome-tweaks-locales
Requires: gnome-tweaks-python
BuildRequires : buildreq-meson

%description
GNOME TWEAKS
================
BUILD
-----
The only build-time dependency is [meson](https://mesonbuild.com/).

%package bin
Summary: bin components for the gnome-tweaks package.
Group: Binaries
Requires: gnome-tweaks-data

%description bin
bin components for the gnome-tweaks package.


%package data
Summary: data components for the gnome-tweaks package.
Group: Data

%description data
data components for the gnome-tweaks package.


%package locales
Summary: locales components for the gnome-tweaks package.
Group: Default

%description locales
locales components for the gnome-tweaks package.


%package python
Summary: python components for the gnome-tweaks package.
Group: Default
Requires: gnome-tweaks-python3

%description python
python components for the gnome-tweaks package.


%package python3
Summary: python3 components for the gnome-tweaks package.
Group: Default
Requires: python3-core

%description python3
python3 components for the gnome-tweaks package.


%prep
%setup -q -n gnome-tweaks-3.30.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536592948
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-tweaks

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-tweaks
/usr/libexec/gnome-tweak-tool-lid-inhibitor

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.tweaks.desktop
/usr/share/gnome-tweaks/shell.css
/usr/share/gnome-tweaks/shell.ui
/usr/share/icons/hicolor/16x16/apps/org.gnome.tweaks.png
/usr/share/icons/hicolor/22x22/apps/org.gnome.tweaks.png
/usr/share/icons/hicolor/24x24/apps/org.gnome.tweaks.png
/usr/share/icons/hicolor/256x256/apps/org.gnome.tweaks.png
/usr/share/icons/hicolor/32x32/apps/org.gnome.tweaks.png
/usr/share/icons/hicolor/48x48/apps/org.gnome.tweaks.png
/usr/share/icons/hicolor/scalable/apps/org.gnome.tweaks-symbolic.svg
/usr/share/metainfo/org.gnome.tweaks.appdata.xml

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f gnome-tweaks.lang
%defattr(-,root,root,-)

